/////////////////////////////////////////////////////////////////////////////
// Copyright © by W. T. Block, all rights reserved
/////////////////////////////////////////////////////////////////////////////
#pragma once
class CPhotoExplorerView;

/////////////////////////////////////////////////////////////////////////////
// CChildFrame
//
// Standard MDI child frame window generated by the MFC Application Wizard.
// In Photo Explorer, each open album (XML *.album file) is displayed inside
// its own child frame. The frame hosts the split view consisting of the
// thumbnail list on the left and the full‑image preview on the right.
//
// Purpose:
//   • Provide the window frame that contains a single document/view pair.
//   • Create and manage the splitter window that divides the thumbnail list
//     and the main image view.
//   • Integrate with MFC’s CMDIChildWndEx to support modern docking,
//     tabbed MDI groups, and Visual Studio–style window management.
//   • Relay view‑style commands (icon, list, thumbnail modes) to the view.
//
// Why this class exists:
//   The MFC Wizard generates a child frame class automatically for MDI
//   applications. Photo Explorer uses this class primarily to:
//       – Create the two‑pane splitter (OnCreateClient)
//       – Host the CPhotoExplorerView on the right pane
//       – Support view‑style switching via OnViewStyle()
//       – Notify the main frame when a different album becomes active
//
// Responsibilities:
//   • Create the splitter window and attach the correct views.
//   • Provide access to the right‑hand view pane (GetRightPane).
//   • Handle view‑style commands and update UI state.
//   • Notify the main frame when activation changes (OnMDIActivate).
//   • Maintain standard MDI child window behavior (caption, sizing,
//     activation, focus).
//
// Wizard‑generated portions:
//   • Class declaration and inheritance from CMDIChildWndEx.
//   • PreCreateWindow override setting standard MDI child styles.
//   • Message map structure.
//   • Debugging helpers (AssertValid, Dump).
//   • Splitter window member (CSplitterWndEx).
//
// Application‑specific additions:
//   • Splitter creation logic in OnCreateClient.
//   • View‑style update handlers (OnUpdateViewStyles / OnViewStyle).
//   • Activation handler that synchronizes the Properties pane and
//     other UI components when switching between albums.
//
// This class provides the structural container for each album’s view,
// enabling Photo Explorer’s multi‑document interface and its split‑pane
// thumbnail/preview layout.
/////////////////////////////////////////////////////////////////////////////
class CChildFrame : public CMDIChildWndEx
{
	DECLARE_DYNCREATE(CChildFrame)
public:
	CChildFrame() noexcept;

// Attributes
protected:
	CSplitterWndEx m_wndSplitter;
public:

// Operations
public:

// Overrides
	public:
	virtual BOOL OnCreateClient(LPCREATESTRUCT lpcs, CCreateContext* pContext);
	virtual BOOL PreCreateWindow(CREATESTRUCT& cs);

// Implementation
public:
	virtual ~CChildFrame();
#ifdef _DEBUG
	virtual void AssertValid() const;
	virtual void Dump(CDumpContext& dc) const;
#endif

protected:
	CPhotoExplorerView* GetRightPane();
// Generated message map functions
protected:
	afx_msg void OnUpdateViewStyles(CCmdUI* pCmdUI);
	afx_msg void OnViewStyle(UINT nCommandID);
	DECLARE_MESSAGE_MAP()
public:
	afx_msg void OnMDIActivate( BOOL bActivate, CWnd* pActivateWnd, CWnd* pDeactivateWnd );
};
