/////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2025 by W. T. Block, All Rights Reserved
/////////////////////////////////////////////////////////////////////////////
#pragma once

/////////////////////////////////////////////////////////////////////////////
// CChildFrame
//
// Standard MDI child frame window generated by the MFC Application Wizard.
// PhotoPrinter does not customize child frames beyond the default behavior,
// so this class remains almost entirely wizard‑generated scaffolding.
//
// Purpose:
//   • Provide the window frame that hosts a single document/view pair
//     inside the MDI interface.
//   • Supply the caption bar, system menu, sizing border, and activation
//     behavior for each open PhotoPrinter document.
//   • Integrate with MFC’s CMDIChildWndEx to support modern docking,
//     tabbed MDI groups, and Visual Studio–style window management.
//
// Why this class exists:
//   In an MDI application, each document is displayed inside its own
//   child frame window. The MFC Wizard creates this class automatically
//   so the application has a proper container for the view (CPhotoPrinterView)
//   and document (CPhotoPrinterDoc).
//
// What is wizard‑generated:
//   • Class declaration and inheritance from CMDIChildWndEx
//   • PreCreateWindow override setting standard MDI child styles
//   • Message map and OnMDIActivate handler stub
//   • Debugging helpers (AssertValid, Dump)
//   • Splitter window member (unused unless manually enabled)
//
// PhotoPrinter customization:
//   The only non‑wizard addition is the OnMDIActivate override, which
//   updates the Properties pane whenever a different document becomes
//   active. This ensures the metadata panel always reflects the currently
//   selected photo book.
//
// Responsibilities:
//   • Host the active view inside the MDI frame.
//   • Notify the main frame when activation changes (OnMDIActivate).
//   • Maintain standard MDI child window behavior (caption, sizing,
//     activation, focus).
//
// This class is intentionally minimal. It exists to satisfy the MDI
// architecture and requires no additional logic for PhotoPrinter’s
// document/view system.
/////////////////////////////////////////////////////////////////////////////
class CChildFrame : public CMDIChildWndEx
{
	DECLARE_DYNCREATE(CChildFrame)
public:
	CChildFrame() noexcept;

// Attributes
protected:
	CSplitterWndEx m_wndSplitter;
public:

// Operations
public:

// Overrides
	public:
	virtual BOOL PreCreateWindow(CREATESTRUCT& cs);

// Implementation
public:
	virtual ~CChildFrame();
#ifdef _DEBUG
	virtual void AssertValid() const;
	virtual void Dump(CDumpContext& dc) const;
#endif

// Generated message map functions
protected:
	DECLARE_MESSAGE_MAP()
	afx_msg void OnMDIActivate(BOOL bActivate, CWnd* pActivateWnd, CWnd* pDeactivateWnd);
};

/////////////////////////////////////////////////////////////////////////////
